version: '3.8'

services:
  web:
    container_name: docker-rails-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:cached
    tty: true
    depends_on:
      - db

  db:
    container_name: docker-rails-db
    image: postgres:12.1-alpine
    volumes:
      - ./docker/db/storage:/var/lib/postgresql/data:cached 
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
      TZ: Asia/Tokyo
